spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice_todolist
    username: martin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api